export const PROGRAM_LIST_REQUEST = 'PROGRAM_LIST_REQUEST';
export const PROGRAM_LIST_SUCCESS = 'PROGRAM_LIST_SUCCESS';
export const PROGRAM_LIST_FAILURE = 'PROGRAM_LIST_FAILURE';
export const PROGRAM_SELECT = 'PROGRAM_SELECT';
export const PROGRAM_CLEAR = 'PROGRAM_CLEAR';
